#!/bin/bash
# Step-by-step guide to train and evaluate ProtoLens on Yelp

echo "=========================================="
echo "ProtoLens Training Guide - Step by Step"
echo "=========================================="
echo ""

# Step 0: Check prerequisites
echo "STEP 0: Checking prerequisites..."
echo "✓ Yelp dataset: $(wc -l /home/mahdi.abootorabi/protovit/ProtoLens/Datasets/Yelp/train.csv | awk '{print $1}') lines"
echo "✓ Python packages installed"
echo ""

# Step 1: Generate prototypes
echo "=========================================="
echo "STEP 1: Generate Prototype Initialization"
echo "=========================================="
echo ""
echo "This creates the prototype cluster centers and representative sentences."
echo "It will take ~10-15 minutes on CPU."
echo ""
echo "Run this command:"
echo ""
echo "  cd /home/mahdi.abootorabi/protovit/ProtoLens"
echo "  python generate_prototypes.py --dataset Yelp --num_prototypes 20 --window_size 5 --max_samples 30000 --max_sub_sentences 15000"
echo ""
echo "Monitor progress with:"
echo "  tail -f prototype_gen_run*.log"
echo ""
echo "Expected output files:"
echo "  Datasets/Yelp/all-mpnet-base-v2/Yelp_cluster_20_centers.npy"
echo "  Datasets/Yelp/all-mpnet-base-v2/Yelp_cluster_20_to_sub_sentence.csv"
echo ""
read -p "Press Enter when prototype generation is complete..."

# Step 2: Fix experiment.py paths
echo ""
echo "=========================================="
echo "STEP 2: Verify Configuration"
echo "=========================================="
echo ""
echo "Check that args.py has correct settings:"
echo "  - data_set: 'Yelp'"
echo "  - num_prototypes: 20"
echo "  - epoch: 25"
echo "  - batch_size: 16"
echo "  - learning_rate: 0.0005"
echo ""

# Step 3: Train model
echo ""
echo "=========================================="
echo "STEP 3: Train Model on Yelp"
echo "=========================================="
echo ""
echo "Run training with:"
echo ""
echo "  cd /home/mahdi.abootorabi/protovit/ProtoLens"
echo "  python experiment.py -d Yelp -pn 20 -e 25 -bs 16 -lr 0.0005 -i 0"
echo ""
echo "Or if you want to modify args.py directly and run:"
echo "  python experiment.py"
echo ""
echo "Training will take ~2-4 hours depending on GPU."
echo "Model will be saved to: log_folder/Yelp/{experiment_name}/model.pth"
echo ""

# Step 4: Evaluate
echo ""
echo "=========================================="
echo "STEP 4: Evaluate Model"
echo "=========================================="
echo ""
echo "The experiment.py script automatically evaluates on validation set."
echo "Check the log file for accuracy: log_folder/Yelp/{experiment_name}/log.txt"
echo ""

echo ""
echo "=========================================="
echo "Summary of Commands"
echo "=========================================="
echo ""
echo "1. Generate prototypes:"
echo "   python generate_prototypes.py --dataset Yelp --num_prototypes 20 --window_size 5 --max_samples 30000 --max_sub_sentences 15000"
echo ""
echo "2. Train model:"
echo "   python experiment.py -d Yelp -pn 20 -e 25 -bs 16 -lr 0.0005"
echo ""
echo "3. Monitor training:"
echo "   tail -f log_folder/Yelp/*/log.txt"
echo ""
